name: Invoice AI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Docker Version
        run: docker --version

      - name: Run Hello World Container
        run: docker run hello-world

      - name: List Running Containers
        run: docker ps -a